org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.5
parchment_mappings_version=2025.04.19
minecraft_version=1.21.5
minecraft_version_range=[1.21.5, 1.22)
neo_version=21.5.66-beta
neo_version_range=[21.5.0-beta,)
loader_version_range=[4,)

mod_id=citruslib
mod_name=CitrusLib
mod_license=MIT
mod_version=2.0.1-1.21.5
mod_group_id=dev.teamcitrus.citruslib
mod_authors=TeamCitrus
mod_description=A small library with our common code for mods!
